#!/bin/bash -e

if [[ -z $VAULT_ADDR || -z $VAULT_TOKEN && ( -z $VAULT_ROLE_ID || -z $VAULT_SECRET_ID ) ]]; then
    echo "The environment variables VAULT_ADDR and VAULT_TOKEN or VAULT_ROLE_ID and VAULT_SECRET_ID are required"
    exit 1
fi

if [ -z $1 ]; then
    echo "Usage: $0 PATH [CURLOPTIONS]"
    exit 1
fi

if [ -z $VAULT_TOKEN ]; then
    VAULT_TOKEN=$(curl -s -d '{"role_id":"'$VAULT_ROLE_ID'","secret_id":"'$VAULT_SECRET_ID'"}' $VAULT_ADDR/v1/auth/approle/login | jq -r '.auth.client_token')
fi

VAULTPATH="$1"
shift 1

exec curl -sH "X-Vault-Token:$VAULT_TOKEN" "$VAULT_ADDR/v1/$VAULTPATH" "$@" | jq
