#!/bin/bash -e

if [ -z "$2" ]; then
    echoerr "Usage: $0 ROLE USER [SSH_KEY_PATH]"
    exit 1
fi

if [ -z "$3" ]; then
    SSH_KEY_PATH="$HOME/.ssh/vault_rsa"
else
    SSH_KEY_PATH="$3"
fi

json_quote() {
    echo '{}' | jq --arg var "$1" '$var'
}

echoerr() {
    printf "%s\n" "$*" >&2
}

if [ ! -d "$(dirname $SSH_KEY_PATH)" ]; then
    install -dm700 "$(dirname $SSH_KEY_PATH)"
fi

if [ ! -f "$SSH_KEY_PATH" ]; then
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY_PATH" -qN ''
fi

ROLE="$1"
USER=$(json_quote "$2")
RSA_KEY=$(json_quote "$(cat "$SSH_KEY_PATH.pub")")

PAYLOAD=$(cat <<EOF
{
  "public_key": $RSA_KEY,
  "valid_principals": $USER
}
EOF
)

if [ ! -f "$SSH_KEY_PATH-cert.pub" ]; then
    RESPONSE=$("$(dirname "$0")"/curl-vault "ssh-client-signer/sign/$ROLE" -X POST -d "$PAYLOAD")
    echo "$RESPONSE"
    echo "$RESPONSE" | jq -r .data.signed_key > "$SSH_KEY_PATH-cert.pub"
fi
