#!/bin/bash -e

NAME=$1

if [ -z "$NAME" ]; then
    echo "Usage: $0 PACKAGE_NAME"
    exit 1
fi

cd "$HOME/rpmbuild"

mkdir -p package/target
rm -f package/target/$NAME-*.src.rpm

spectool -g -R package/$NAME.spec
rpmbuild -bs --nodeps package/$NAME.spec
yum-builddep -y package/$NAME.spec
rpmbuild --rebuild package/target/$NAME-*.src.rpm
